import Link from "next/link";
import React from "react";
import getAll from "../lib/getAll";

export const metadata = {
  title: "Blog Section",
  description: "Generated by create next app",
};
const blogs = async () => {
  const blogs = await getAll();

  return (
    <ul className="">
      {blogs.map((blog) => (
        <li key={blog.id}>
          <Link href={`/blogs/${blog.id}`}>{blog.id}</Link>
        </li>
      ))}
    </ul>
  );
};

export default blogs;
