import Link from "next/link";
import React, { Suspense } from "react";
import getAll from "../lib/getAll";
import getAllPost from "../lib/getAllPost";
import Posts from "../components/Posts";
import Loading from "../components/Loading";

export const metadata = {
  title: "Blog Section",
  description: "Generated by create next app",
};
const blogs = async () => {
  const blogs = await getAll();
  const posts = getAllPost();

  return (
    <ul className="">
      {blogs.map((blog) => (
        <li key={blog.id}>
          <Link href={`/blogs/${blog.id}`}>{blog.id}</Link>
        </li>
      ))}
      <Suspense fallback={<Loading />}>
        <div>Other</div>
        <Posts promise={posts}></Posts>
      </Suspense>
    </ul>
  );
};

export default blogs;
